# Generated by Django 3.1 on 2020-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bothard', '0002_auto_20200827_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='obstacles',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='today',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='yesterday',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
